# -*- coding: utf-8 -*-
"""GIFCreator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-7avjO0fCMaBAdD3Z-4lWNb-AKmu1Wm
"""

import os
from moviepy.editor import *

clip = (VideoFileClip\
        ("football.mp4", audio=False)
      .resize(.5)
      .subclip(12.33,12.93)
      .speedx(.5))

clip.write_gif("football.gif")

